### ISSUE TITLE
`#'=q` in intro doesn't work

### ISSUE THREAD

**Issue by jordancurve** [estradajke/k9-simples#1]
The line of code ` #'=q` in the intro gives the error `!nyi` under k 2020.06.11.

**Comment by jordancurve** [comment]
On [the k tree](https://chat.stackexchange.com/transcript/message/54669629#54669629), ngn suggested ` #'=+(+q)[]`, which seems to work.

**Comment by estradajke** [comment]
Thanks and fixed.  I was hoping that #'=q would come back given it's easier to read but not there yet.
