### ISSUE TITLE
Feature Request:  describe ?0. (rand) a bit more

### ISSUE THREAD

**Issue by anujgoyal** [estradajke/k9-simples#10]
Your document is great!  Can you create a section near 4.33 that describes the different types of rands?

eg. 

 5?0a
181997966 1766800925 1527163350 1528744538 1926857488
 5?0b
00000b
 5?0c
87879518 1893379807 482693011 1702298524 1215456181
 5?0d
^0 2 2 2 4d
 5?0e
0. 0. 0. 0. 0.
 5?0f
0. 0. 0. 0. 0.
 5?0g
221 45 225 15 203
 5?0h
12035 52023 62339 32672 40448
 5?0i
547190726 924849954 99349345 31887227 931271307
 5?0j
5256785715952467465 7960654020936294374 7060561257844673622 7504660024989211339 4809681053323853382
 5?0k
uuid uuid uuid uuid uuid
 5?0l
2083632368 828538470 466893136 217704295 1691644614

**Comment by estradajke** [comment]
I don't really understand these, eg. 5?0i, so no doc updates yet.  I've updated the docs on the more clear examples, eg. 3?5. though.

**Comment by estradajke** [comment]
Might as well leave this open until it's sorted.

**Comment by anujgoyal** [comment]
this might help...  also - do you have a type table somewhere in your docs?

 @ 1?0a
`I
 @ 1?0b
`B
 @ 1?0c
`I
 @ 1?0d
`D
 @ 1?0e
`E
 @ 1?0f
`F
 @ 1?0g
`G
 @ 1?0h
`H
 @ 1?0i
`I
 @ 1?0j
`J
 @ 1?0k
`K
 @ 1?0l
`I
 @ 1?0m
`M

etc.

**Comment by estradajke** [comment]
I have this...

The set of k9 data, aka nouns, are as follows.

Atom   Example     
bool,  011b           
int,   0N 2 3       
flt,   0n 2 3.4     
char,  " ab"          
name,  ``ab
uuid,  
time,  12:34:56.123456789   
date, 2024.01.01T12:34:56 

and then if you go to a type then you get a bit more detail.

6.2.1 int ⇒ Integer I

Let me know what you think would make this more clear and happy to have a go at improving it.

**Comment by estradajke** [comment]
"invalid tokens just go to 0 right now."

I'll close this out as I don't know when this will be changed in the language.
