### ISSUE TITLE
$[x;y;z] is not a function

### ISSUE THREAD

**Issue by adotsch** [estradajke/k9-simples#11]
Hi,

First of all, thank for putting this doc together, very useful!
In 11. chapter you write cond ($[x;y;z]) is a function. Actually, it is a (lazy) language construct, the y or z expression is evaluated based on x. You can easily verify this by running $[0;a:10;b:20] and checking a and b.

Regards,
Andras

**Comment by estradajke** [comment]
Hey Andras.  Any thoughts on what the chapter might be called instead?  It's only cond, amend, and dmend for now.

$[b;x;y] if else
@[x;i;f[;y]] amend
.[x;i;f[;y]] dmend

**Comment by adotsch** [comment]
Hi,

I think cond should go into execution control. Later you may add
if/do/while there when Arthur implements them.
At and dot should go into "Functional amend" or "General Application" just
like in Q for Mortals (
https://code.kx.com/q4m3/6_Functions/#68-general-application).

Regards,
András

**Comment by estradajke** [comment]
Done with slightly different labels.
