### ISSUE TITLE
`-1#+\q` in intro gives differently-formatted output with k 2020.06.11

### ISSUE THREAD

**Issue by jordancurve** [estradajke/k9-simples#3]
In the [intro](https://estradajke.github.io/k9-simples/k9/Intro.html), ` -1#+\q` gives the wrong output format with k 2020.06.11.

Expected intput/output (the numbers themselves don't matter; I'm only showing this for the formatting):

```
 -1#+\q
a   b   c 
--- --- --
-68 117 73
```

Observed input/output (note different format of output compared to expected):

```
 -1#+\q
[[]a:,-14;b:,-64;c:,-45]
```

**Comment by estradajke** [comment]
corrected and fixed to dictionary as I don't think one line tables are readable.
