### ISSUE TITLE
`{(+/m*m:x-avg x)%#x}'+q` in intro doesn't work with k 2020.06.11

### ISSUE THREAD

**Issue by jordancurve** [estradajke/k9-simples#5]
The code `{(+/m*m:x-avg x)%#x}'+q ` from the [intro](https://estradajke.github.io/k9-simples/k9/Intro.html) doesn't work with k 2020.06.11.

Expected input/output:

```
 {(+/m*m:x-avg x)%#x}'+q
a|0.6601538
b|0.6629631
c|0.6708467
```

Observed input/output:

```
 {(+/m*m:x-avg x)%#x}'+q 
{(+/m*m:x-avg x)%#x}'+q 
 ^
!parse
```

**Comment by estradajke** [comment]
fixed and thanks
